# Generated by Django 5.2.1 on 2025-10-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biolink', '0002_remove_link_user_alter_link_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biolinkprofile',
            name='public_id',
        ),
    ]
