# Generated by Django 5.2.1 on 2025-12-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biolink', '0003_remove_biolinkprofile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biolinkprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
