# Generated by Django 5.2.1 on 2025-12-14 05:54

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biolink', '0004_alter_biolinkprofile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biolinkprofile',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
