# Generated by Django 5.2.1 on 2025-08-15 13:08

import django.db.models.deletion
import urlLogic.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(unique=True, validators=[urlLogic.models.validate_url_format_and_blacklist])),
                ('short_url', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qr_code/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UrlVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('browser', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='urlLogic.urlmodel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
