# Generated by Django 5.2.1 on 2025-07-26 10:21

import django.db.models.deletion
import urlLogic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlLogic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='original_url',
            field=models.URLField(unique=True, validators=[urlLogic.models.validate_url_format_and_blacklist]),
        ),
        migrations.CreateModel(
            name='UrlVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('browser', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='urlLogic.urlmodel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
