# Generated by Django 5.2.1 on 2025-05-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlLogic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmodel',
            old_name='short_code',
            new_name='short_url',
        ),
    ]
