# Generated by Django 5.2.1 on 2025-05-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlLogic', '0002_rename_short_code_urlmodel_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/'),
        ),
    ]
