# Generated by Django 5.2.1 on 2025-10-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlLogic', '0003_shorturlanonymous_ip_address_urlvisit_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlvisit',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='urlvisit',
            name='screen_resolution',
        ),
    ]
