# Generated by Django 5.2.1 on 2025-05-29 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlLogic', '0003_urlmodel_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
