# Generated by Django 5.2.1 on 2025-05-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlLogic', '0004_alter_urlmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='original_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='short_url',
            field=models.CharField(max_length=10),
        ),
    ]
