# Generated by Django 5.2.1 on 2025-10-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlLogic', '0004_remove_urlvisit_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlvisit',
            name='http_method',
        ),
        migrations.RemoveField(
            model_name='urlvisit',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='urlvisit',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='urlvisit',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='urlvisit',
            name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='urlvisit',
            name='utm_medium',
        ),
        migrations.RemoveField(
            model_name='urlvisit',
            name='utm_source',
        ),
    ]
