# Generated by Django 5.2.1 on 2025-11-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlLogic', '0005_remove_urlvisit_http_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
