# Generated by Django 5.2.1 on 2025-12-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlLogic', '0006_alter_urlmodel_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlmodel',
            options={'ordering': ['-created_at']},
        ),
    ]
