# Generated by Django 5.2.1 on 2026-01-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Blog',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='blogprofile',
            name='social_links',
        ),
        migrations.AddField(
            model_name='blogprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='blog_blog_slug_d925e3_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status'], name='blog_blog_status_e6780b_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['published_at'], name='blog_blog_publish_097daa_idx'),
        ),
    ]
