from django.db import models
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from urllib.parse import urlparse
from cloudinary_storage.storage import MediaCloudinaryStorage

User = get_user_model()

# Optional: list of disallowed domains (e.g., your own app domain to prevent recursive short URLs)
BLACKLISTED_DOMAINS = [
    "url-ly.onrender.com",
    "localhost",
    "127.0.0.1",
]


def validate_url_format_and_blacklist(value):
    parsed_url = urlparse(value)
    print(parsed_url)

    if not parsed_url.scheme or not parsed_url.netloc:
        raise ValidationError("Invalid URL format.")

    domain = parsed_url.netloc.lower()

    for blocked in BLACKLISTED_DOMAINS:
        if blocked in domain:
            raise ValidationError("This domain is not allowed.")


class UrlModel(models.Model):
    # id field is auto generated by django
    original_url = models.URLField(
        unique=True, validators=[validate_url_format_and_blacklist]
    )
    short_url = models.CharField(max_length=10, unique=True, null=True, blank=True)
    qrcode = models.ImageField(
        upload_to="qr_code/", null=True, blank=True, storage=MediaCloudinaryStorage()
    )
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    click_count = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.short_url}"


class UrlVisit(models.Model):
    url = models.ForeignKey("UrlModel", on_delete=models.CASCADE, related_name="visits")
    timestamp = models.DateTimeField(auto_now_add=True)
    ip_address = models.GenericIPAddressField()
    browser = models.CharField(max_length=50)
    os = models.CharField(max_length=50)
    device = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        ordering = ["-timestamp"]
